# Generated by Django 4.2 on 2026-01-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('title_kk', models.CharField(blank=True, max_length=300, verbose_name='Заголовок (каз.)')),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('excerpt_kk', models.TextField(blank=True, max_length=500, verbose_name='Краткое описание (каз.)')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('content_kk', models.TextField(blank=True, verbose_name='Содержимое (каз.)')),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='Изображение')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title_kk', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (каз.)')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('content_kk', models.TextField(blank=True, verbose_name='Содержимое (каз.)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=300, verbose_name='Название организации')),
                ('org_name_kk', models.CharField(blank=True, max_length=300, verbose_name='Название (каз.)')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('address_kk', models.TextField(blank=True, verbose_name='Адрес (каз.)')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('bin_iin', models.CharField(max_length=12, verbose_name='БИН/ИИН')),
                ('bank_details', models.TextField(blank=True, verbose_name='Банковские реквизиты')),
                ('accreditation_cert', models.FileField(blank=True, upload_to='org/', verbose_name='Свидетельство об аккредитации')),
                ('charter', models.FileField(blank=True, upload_to='org/', verbose_name='Устав')),
                ('logo', models.ImageField(blank=True, upload_to='org/', verbose_name='Логотип')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
