# Generated by Django 4.2 on 2026-01-27 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('name_kk', models.CharField(blank=True, max_length=100, verbose_name='Название (каз.)')),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория документов',
                'verbose_name_plural': 'Категории документов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('title_kk', models.CharField(blank=True, max_length=300, verbose_name='Название (каз.)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_kk', models.TextField(blank=True, verbose_name='Описание (каз.)')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documentcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['category', 'order', 'title'],
            },
        ),
    ]
