# Generated by Django 4.2 on 2026-01-27 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('last_name_kk', models.CharField(blank=True, max_length=100, verbose_name='Фамилия (каз.)')),
                ('first_name_kk', models.CharField(blank=True, max_length=100, verbose_name='Имя (каз.)')),
                ('middle_name_kk', models.CharField(blank=True, max_length=100, verbose_name='Отчество (каз.)')),
                ('iin', models.CharField(max_length=12, unique=True, verbose_name='ИИН')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специализация')),
                ('specialization_kk', models.CharField(blank=True, max_length=200, verbose_name='Специализация (каз.)')),
                ('education', models.TextField(verbose_name='Образование (ВУЗ, год, специальность)')),
                ('education_kk', models.TextField(blank=True, verbose_name='Образование (каз.)')),
                ('workplace', models.CharField(max_length=300, verbose_name='Основное место работы')),
                ('workplace_kk', models.CharField(blank=True, max_length=300, verbose_name='Место работы (каз.)')),
                ('workplace_address', models.CharField(blank=True, max_length=300, verbose_name='Адрес места работы')),
                ('experience_years', models.PositiveIntegerField(verbose_name='Стаж в здравоохранении (лет)')),
                ('registry_date', models.DateField(verbose_name='Дата включения в реестр')),
                ('registry_number', models.CharField(max_length=50, unique=True, verbose_name='Номер в реестре')),
                ('expertise_count', models.PositiveIntegerField(default=0, verbose_name='Количество проведённых экспертиз')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='experts/photos/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Эксперт',
                'verbose_name_plural': 'Эксперты',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название профиля')),
                ('name_kk', models.CharField(blank=True, max_length=100, verbose_name='Название (каз.)')),
                ('slug', models.SlugField(unique=True)),
                ('profile_type', models.CharField(choices=[('therapeutic', 'Терапевтический'), ('surgical', 'Хирургический'), ('obstetric', 'Акушерско-гинекологический'), ('pediatric', 'Педиатрический'), ('other', 'Другой')], default='other', max_length=20, verbose_name='Тип профиля')),
            ],
            options={
                'verbose_name': 'Профиль эксперта',
                'verbose_name_plural': 'Профили экспертов',
            },
        ),
        migrations.CreateModel(
            name='ExpertCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(choices=[('diploma', 'Диплом'), ('certificate', 'Сертификат специалиста'), ('qualification', 'Повышение квалификации'), ('other', 'Другой документ')], max_length=20, verbose_name='Тип документа')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('title_kk', models.CharField(blank=True, max_length=300, verbose_name='Название (каз.)')),
                ('issuer', models.CharField(max_length=300, verbose_name='Кем выдан')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Срок действия')),
                ('hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество часов')),
                ('document', models.FileField(upload_to='experts/certificates/', verbose_name='Файл документа')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='experts.expert', verbose_name='Эксперт')),
            ],
            options={
                'verbose_name': 'Сертификат эксперта',
                'verbose_name_plural': 'Сертификаты экспертов',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.AddField(
            model_name='expert',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experts', to='experts.expertprofile', verbose_name='Профиль'),
        ),
    ]
