# Generated by Django 4.2 on 2026-01-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('title_kk', models.CharField(blank=True, max_length=500, verbose_name='Название (каз.)')),
                ('pub_type', models.CharField(choices=[('article', 'Научная статья'), ('book', 'Книга/Монография'), ('thesis', 'Диссертация'), ('guideline', 'Методические рекомендации'), ('patent', 'Патент/Изобретение'), ('other', 'Другое')], max_length=20, verbose_name='Тип публикации')),
                ('authors_text', models.CharField(help_text='Укажите всех авторов, включая внешних', max_length=500, verbose_name='Авторы (текст)')),
                ('journal', models.CharField(blank=True, max_length=300, verbose_name='Журнал/Издательство')),
                ('year', models.PositiveIntegerField(verbose_name='Год публикации')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='Том/Выпуск')),
                ('pages', models.CharField(blank=True, max_length=50, verbose_name='Страницы')),
                ('doi', models.CharField(blank=True, max_length=100, verbose_name='DOI')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('file', models.FileField(blank=True, null=True, upload_to='publications/', verbose_name='Файл публикации')),
                ('abstract', models.TextField(blank=True, verbose_name='Аннотация')),
                ('abstract_kk', models.TextField(blank=True, verbose_name='Аннотация (каз.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='publications', to='experts.expert', verbose_name='Авторы (эксперты)')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['-year', 'title'],
            },
        ),
    ]
